version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myapppassword
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myappuser
      DB_PASSWORD: myapppassword
      DB_NAME: myappdb
      DEFAULT_USER: testuser
      USER_PASS: "12345"
      JWT_KEY: "mysecretkey"
    ports:
      - "8000:8000"
    restart: unless-stopped
